version: '3.8'
services:
  financial-management-database:
    image: postgres:16.1-alpine
    container_name: financial-management-database
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '5490:5455'
    command: -p 5455
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=financial-management
      - POSTGRES_PASSWORD=
